# Generated by Django 3.2 on 2022-11-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='work_study_place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
