# Generated by Django 3.2 on 2022-11-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_mentor_main_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='emal',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='emal',
            new_name='email',
        ),
    ]
